apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
            - containerPort: 4000
