# Stage 1: Build
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY . .

# Stage 2: Run
FROM node:18-alpine
WORKDIR /app
# 'builder' stage se sirf optimized files uthao
COPY --from=builder /app .

EXPOSE 3000
USER node
CMD ["node", "app.js"]
