backend:
  image:
    repository: devopsdockerhub461/backend
    tag: latest  # Ye niche wala --set ise override karega

frontend:
  image:
    repository: devopsdockerhub461/frontend
    tag: latest
